k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /Users/omykyte/Library/Application Support/k9s/screen-dumps
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 2
  readOnly: false
  noExitOnCtrlC: false
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: true
    logoless: true
    crumbsless: false
    splashless: false
    reactive: true
    noIcons: false
    defaultsToFullScreen: false
    useFullGVRTitle: false
    skin: nord
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: true
    disableAutoscroll: false
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  defaultView: ""
